name: Check

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  check-distro:
    runs-on: ubuntu-latest
    container: debian:unstable

    steps:
      - name: Install prerequisites via apt
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          set -ex
          apt update
          apt install -y git
      - uses: actions/checkout@v4
      # - name: Workaround for https://github.com/actions/checkout/pull/762 not persisting
      #   run: git config --global --add safe.directory "$PWD"
      - name: git
        run: |
          set -ex
          git status
